services:
  python_app:
    container_name: fastapi_backend
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    env_file:
      - ./.env
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "8001:8001"
    depends_on:
      - db

  db:
    image: postgres:17-alpine
    shm_size: 2g
    container_name: postgres
    env_file:
      - ./.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE}
      PGDATA: /var/lib/postgresql/data/
    healthcheck:
        test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d ${DB_DATABASE}"]
        interval: 30s
        timeout: 60s
        retries: 5
        start_period: 80s

  redis:
    image: redis:latest
    container_name: my-redis
    ports:
        - '6379:6379'
    volumes:
        - redis-data:/data
    environment:
        - REDIS_ARGS=--requirepass your_password_here --appendonly yes
    restart: unless-stopped
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgAdmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.admin
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  postgres_data:
  redis-data:
    driver: local
